# pdf_generator.py
from fpdf import FPDF
from datetime import datetime

class ExecutivePolicyPDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(30, 41, 59)
        self.cell(0, 8, 'PEMERINTAH DAERAH / DINAS KOMUNIKASI DAN INFORMATIKA', ln=True, align='C')
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(100, 116, 139)
        self.cell(0, 6, 'DECISION SUPPORT BRIEF: INTERNET DESA INFRASTRUCTURE ALLOCATION', ln=True, align='C')
        self.ln(3)
        self.set_draw_color(203, 213, 225)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Generated by TOPSIS Decision Engine on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} | Page {self.page_no()}', align='C')

def create_policy_pdf(df_ranked, weights_dict, lang_code='en'):
    pdf = ExecutivePolicyPDF()
    pdf.add_page()
    
    # 1. Executive Summary Block
    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 7, '1. Executive Summary & Policy Parameters', ln=True)
    pdf.set_font('Helvetica', '', 9.5)
    summary_text = (
        "This official policy recommendation provides a prioritized ranking for rural broadband deployment "
        "using Multi-Criteria Decision Analysis (TOPSIS). Weights were assigned according to strategic public interest."
    )
    pdf.multi_cell(0, 5, summary_text)
    pdf.ln(3)

    # 2. Weights Summary Table
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(95, 6, 'Criteria Name', 1, 0, 'L', fill=True)
    pdf.cell(95, 6, 'Assigned Weight (%)', 1, 1, 'C', fill=True)

    pdf.set_font('Helvetica', '', 9)
    criteria_names = {
        'w_penduduk': 'Population Size',
        'w_kemiskinan': 'Poverty Rate',
        'w_jarak': 'Distance to Urban Center',
        'w_sinyal': 'Signal Need Urgency',
        'w_sekolah': 'Educational Facilities (Schools)'
    }
    for k, v in weights_dict.items():
        pdf.cell(95, 5.5, f"  {criteria_names.get(k, k)}", 1, 0, 'L')
        pdf.cell(95, 5.5, f"{int(v)}%", 1, 1, 'C')
    pdf.ln(5)

    # 3. Top 10 Priority Table
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 7, '2. Priority Deployment Recommendations (Top 10 Villages)', ln=True)
    
    pdf.set_font('Helvetica', 'B', 8.5)
    pdf.set_fill_color(226, 232, 240)
    pdf.cell(12, 6, 'Rank', 1, 0, 'C', fill=True)
    pdf.cell(45, 6, 'Village Name', 1, 0, 'L', fill=True)
    pdf.cell(28, 6, 'TOPSIS Score', 1, 0, 'C', fill=True)
    pdf.cell(35, 6, 'Existing Signal', 1, 0, 'C', fill=True)
    pdf.cell(35, 6, 'Poverty Rate (%)', 1, 0, 'C', fill=True)
    pdf.cell(35, 6, 'Schools Count', 1, 1, 'C', fill=True)

    pdf.set_font('Helvetica', '', 8.5)
    for rank, (_, row) in enumerate(df_ranked.head(10).iterrows(), start=1):
        pdf.cell(12, 5.5, str(rank), 1, 0, 'C')
        pdf.cell(45, 5.5, f" {row['nama_desa']}", 1, 0, 'L')
        pdf.cell(28, 5.5, f"{row['topsis_score']:.4f}", 1, 0, 'C')
        pdf.cell(35, 5.5, str(row['status_sinyal_eksisting']), 1, 0, 'C')
        pdf.cell(35, 5.5, f"{row['persentase_kemiskinan']:.1f}%", 1, 0, 'C')
        pdf.cell(35, 5.5, str(row['jumlah_sekolah']), 1, 1, 'C')
    pdf.ln(6)

    # 4. Official Sign-Off Block
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(100, 5, 'Prepared By:', 0, 0, 'L')
    pdf.cell(90, 5, 'Approved for Execution:', 0, 1, 'L')
    pdf.ln(12)
    pdf.set_font('Helvetica', '', 8.5)
    pdf.cell(100, 4, '_______________________________', 0, 0, 'L')
    pdf.cell(90, 4, '_______________________________', 0, 1, 'L')
    pdf.cell(100, 4, 'Data Intelligence Specialist', 0, 0, 'L')
    pdf.cell(90, 4, 'Kepala Dinas Kominfo / Bappeda', 0, 1, 'L')

    return bytes(pdf.output())